version: '3.8'

services:
  monitoringforupdate-nostalgiaforinfinityx5:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LANGUAGE: ${LANGUAGE}  # Передаем переменную LANGUAGE
    container_name: monitoringforupdate-nostalgiaforinfinityx5-container
    restart: always
    env_file:
      - .env  # Указываем, что нужно использовать файл .env
    c:
      - ${LOCAL_VOLUME_PATH}:/app/Update  # Используем переменную среды для локального пути
      - ./MonitoringForUpdateStratagiaRU.py:/app/MonitoringForUpdateStratagiaRU.py
      - ./MonitoringForUpdateStratagiaENG.py:/app/MonitoringForUpdateStratagiaENG.py
    ports:
      - "8000:8000"  # Пример проброса порта (если необходимо)
    logging:
      driver: "json-file"  # Логирование в json
      options:
        max-size: "10m"      # Максимальный размер файла лога
        max-file: "3"        # Количество логов (файлов)
