version: '3.8'

services:
  monitoringforupdate-nostalgiaforinfinityx5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitoringforupdate-nostalgiaforinfinityx5-container
    restart: always
    env_file:
      - .env  # Указываем, что нужно использовать файл .env
    volumes:
      - ${LOCAL_VOLUME_PATH}:/app/Update  # Используем переменную среды для локального пути
      - ./MonitoringForUpdateStratagia.py:/app/MonitoringForUpdateStratagia.py  # Монтируем ваш скрипт
    ports:
      - "8000:8000"  # Пример проброса порта (если необходимо)
    logging:
      driver: "json-file"  # Логирование в json
      options:
        max-size: "10m"      # Максимальный размер файла лога
        max-file: "3"        # Количество логов (файлов)
