version: '3.8'

services:
  monitoringforupdate-nostalgiaforinfinityx5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitoringforupdate-nostalgiaforinfinityx5-container
    restart: always
    env_file:
      - .env
    volumes:
      - ${LOCAL_VOLUME_PATH}:/app/Update
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
